# Schema for the configuration files of the Telephone type module.

field.formatter.settings.telephone_type_link:
  type: mapping
  label: 'Telephone type link format settings'

field.widget.settings.telephone_type_default:
  type: mapping
  label: 'Telephone type default format settings'
